### ISSUE TITLE
Improve the readme.

### ISSUE THREAD

**Issue by indualagarsamy** [ParticularLabs/RoutingVisualization#1]
I think the readme can be improved.

Talk about why - First and foremost, why did we create this tool?
Talk about what - What does this tool do? 
Talk about how - Talk about how we accomplish the visualization and what are the steps to get it going on an existing visual studio solution. 

Relates to https://github.com/particular/platformdevelopment/issues/454

**Comment by mikeminutillo** [comment]
@indualagarsamy I cleaned up the readme, included a sample and some screenshots and made it more friendly overall. I also updated the code to provide better guidance when common things fail (can't connect to ServiceControl, forgot the .dgml extension, etc.)

Could you please review and tell me if you think it needs any more?

**Comment by indualagarsamy** [comment]
@mikeminutillo - Thank you. I think its great.
